using Documenter, GALAHAD

makedocs(
  modules = [GALAHAD],
  doctest = true,
  linkcheck = true,
  strict = true,
  format = Documenter.HTML(assets = ["assets/style.css"],
                           ansicolor = true,
                           prettyurls = get(ENV, "CI", nothing) == "true",
                           collapselevel = 1),
  sitename = "GALAHAD.jl",
  pages = ["Home" => "index.md", # galahad.md
           "arc" => "arc.md",
           "bgo" => "bgo.md",
           "blls" => "blls.md",
           "bqpb" => "bqpb.md",
           "bqp" => "bqp.md",
           "bsc" => "bsc.md",
           "ccqp" => "ccqp.md",
           "clls" => "clls.md",
           "convert" => "convert.md",
           "cqp" => "cqp.md",
           "cro" => "cro.md",
           "dgo" => "dgo.md",
           "dps" => "dps.md",
           # "dqp" => "dqp.md",
           "eqp" => "eqp.md",
           "fdc" => "fdc.md",
           "fit" => "fit.md",
           #"glrt" => "glrt.md",
           "gls" => "gls.md",
           "gltr" => "gltr.md",
           "hash" => "hash.md",
           "icfs" => "icfs.md",
           "ir" => "ir.md",
           # "l2rt" => "l2rt.md",
           "lhs" => "lhs.md",
           "lms" => "lms.md",
           "lpa" => "lpa.md",
           "lpb" => "lpb.md",
           "lsqp" => "lsqp.md",
           "lsrt" => "lsrt.md",
           "lstr" => "lstr.md",
           "nls" => "nls.md",
           "presolve" => "presolve.md",
           "psls" => "psls.md",
           # "qpa" => "qpa.md",
           "qpb" => "qpb.md",
           "roots" => "roots.md",
           "rpd" => "rpd.md",
           "rqs" => "rqs.md",
           "sbls" => "sbls.md",
           "scu" => "scu.md",
           "sec" => "sec.md",
           "sha" => "sha.md",
           "sils" => "sils.md",
           "slls" => "slls.md",
           "sls" => "sls.md",
           "trb" => "trb.md",
           "trs" => "trs.md",
           "tru" => "tru.md",
           "ugo" => "ugo.md",
           "uls" => "uls.md",
           "wcp" => "wcp.md",
           "Reference" => "reference.md"
          ]
)

deploydocs(
  repo = "github.com/amontoison/GALAHAD.jl.git",
  push_preview = true,
  devbranch = "main",
)
